apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: amazapp
  template:
    metadata:
      labels:
        app: amazapp
    spec:
      containers:
        - name: amazapp
          image: 694322569254.dkr.ecr.ap-south-1.amazonaws.com/amazapp:latest
          ports:
            - containerPort: 5000
